name: Build and publish pre-release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Install Garble
      run: go install mvdan.cc/garble@latest

    - name: Build
      run: ./build.ps1
      shell: pwsh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Binaries
        path: binaries/*

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "prerelease"
        prerelease: true
        title: "Development Build"
        files: |
          binaries/*